FROM node:7-alpine
ARG PROJECT_NAME=super-mean
ENV PROJECT_DIRECTORY="/opt/$PROJECT_NAME/"
RUN mkdir -p "$PROJECT_DIRECTORY"
WORKDIR "$PROJECT_DIRECTORY"
COPY package.json "$PROJECT_DIRECTORY"
COPY . "$PROJECT_DIRECTORY"
RUN npm install
CMD [ "echo", "hi" ]